### ISSUE TITLE
간단 코드 리뷰 

### ISSUE THREAD

**Issue by flynnpark** [Nomad-Coder-React-Challenges/18-final-push#4]
안녕하세요, 재환님! 간단하게 코드리뷰 해보겠습니다~

으음 사실 위 인사 쓰고 코드 쭉 봤는데... 제가 리뷰할 게 따로 없는 것 같습니다... 그냥 궁금한 점이 몇 가지 있는데, 그것만 써보겠습니다.

```ts
const res: GetResponse<IAPIResponse<IMovie[]>> = await instance.get(
  `${category}`
);
```

저 같은 경우는 `instance.get<응답 타입>(...)` 이렇게 쓰고 있는데, 위와 같은 방식으로 쓰신 이유가 따로 있을까요!? 뭐 다른 아쉬운 점은... 따로 없네요...... 그냥 콘솔 남아있는 거 정도...... 잘 봐씃ㅂ니다...

**Comment by lieblichoi** [comment]
오 플린님 바쁘신 와중에 리뷰 남겨주셔서 감사합니다 :)

부족한게 많지만 몇 가지 이유를 말씀드리자면 아래와 같습니다.

플린님께서 쓰고 계시는 방법도 API 요청 중에 응답 타입을 명시한다는 점에서 제가 선택한 방식보다 빠르게 오류 대처가 가능하다는 장점을 가지고 있습니다. 그럼에도 응답을 변수에 할당한 다음에 타입을 명시하는 방식을 선택한 이유는 유연한 오류 대처가 가능하다는 점에 있습니다. 백-프론트 간 컨벤션을 확실하게 정한다고 하더라도 여러가지 이유로 API가 예상치 못한 데이터 구조를 반환하는 경우가 생기고는 합니다. 프론트에서는 잘못된 데이터가 넘어오더라도 웹 페이지 전체가 에러로 인해 튕기는 것만은 피해야하기 때문에 위와 같은 변수 할당 방식을 채택하게 되었습니다. 이런 방식 말고도 옵셔널 체이닝을 적극 활용하는 등 프론트 단에서의 보수적인 코드 작성 방식을 선호하는 편입니다..!

콘솔은... NextJS의 `removeConsole: process.env.NODE_ENV === 'production',` 요 코드 때문에 익숙해져 신경을 덜 쓰다보니 미처 지우지를 못했던 것 같네요 😅

리뷰 남겨주셔셔 감사합니다! 🙏
